import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>)
{
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}


// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const outfit = localFont({
//   src: [
//     {
//       path: "../public/fonts/Outfit-Regular.woff2",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../public/fonts/Outfit-Medium.woff2",
//       weight: "500",
//       style: "normal",
//     },
//     {
//       path: "../public/fonts/Outfit-SemiBold.woff2",
//       weight: "600",
//       style: "normal",
//     },
//     {
//       path: "../public/fonts/Outfit-Bold.woff2",
//       weight: "700",
//       style: "normal",
//     },
//   ],
//   variable: "--font-primary",
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Brocado",
//   description: "O delivery que respeita o seu negócio",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="pt-BR" className={outfit.variable}>
//       <body>{children}</body>
//     </html>
//   );
// }
